### ISSUE TITLE
Nextest is not being run recursively

### ISSUE THREAD

**Issue by def-** [taiki-e/cargo-llvm-cov#260] opened 2023-04-21 12:15 UTC
I tried using `cargo llvm-cov nextest run` on https://github.com/MaterializeInc/materialize/, but only the top-level tests seem to be run:
```
    Starting 17 tests across 102 binaries (523 skipped)
```
Meanwhile `cargo nextest run` is correctly traversing all the recursive Cargo.toml files and running the tests in them too:
```
    Starting 537 tests across 102 binaries (3 skipped)
```
Is this expected or am I missing something?

**Comment by taiki-e** [comment] 2023-04-21 12:19
> `cargo llvm-cov nextest run`

`cargo llvm-cov nextest` internally calls `cargo nextest run`. The last `run` is unneeded.

**Comment by taiki-e** [comment] 2023-04-21 12:30
Duplicate of #233.

**Closed by taiki-e** 2023-04-21 12:30 UTC
Labels: A-nextest
