### ISSUE TITLE
Interoperability with trybuild

### ISSUE THREAD

**Issue by jhpratt** [taiki-e/cargo-llvm-cov#32] opened 2021-06-15 08:55 UTC
Currently, the trybuild crate does not contribute anything to the coverage report. I'm not sure whether this should be fixed in cargo-llvm-cov or trybuild. compiletest_rs, on the other hand, _does_ contribute to the coverage report (but is far more finicky).

**Comment by taiki-e** [comment] 2021-06-23 09:47
I'm not sure what we can do about this on our side...

- The code that trybuild generates for tests is located in "target/tests".
- The path to the object file will be collected in the `object_files` function.
- The `object_files` function does not currently search "target/tests/target".
- However, I tried a change a while ago to search for "target/tests/target", but the coverage results did not change.

https://github.com/taiki-e/cargo-llvm-cov/blob/a04fcab09be3d5993169a83f480cf6c0c2cfe219/src/main.rs#L142-L170

**Comment by jhpratt** [comment] 2021-06-23 23:29
Hmm…that's odd. What does compiletest_rs do differently that it _is_ covered?

**Comment by jhpratt** [comment] 2021-08-07 10:01
Just coming back to this. I just looked through trybuild's code and see nothing that could conceivably be changed to help this. It (unfortunately) looks like this has to be handled on llvm-cov's end if my understanding is correct. As far as I can tell the bullet points you've listed are correct as they relate to trybuild.

**Comment by taiki-e** [comment] 2021-08-07 11:04
I just found a way to fix this.

**Comment by taiki-e** [comment] 2021-08-07 16:30
This will be fixed by #44 and https://github.com/dtolnay/trybuild/pull/121.

**Comment by jhpratt** [comment] 2021-08-07 18:37
You're a wizard, what can I say. You always find a way to do things, and generally quite quickly at that.

**Comment by davidhewitt** [comment] 2021-08-07 22:37
🚀 thank you, really excited to see this!

**Comment by taiki-e** [comment] 2021-08-10 18:16
trybuild 1.0.44 yanked due to regression: https://github.com/dtolnay/trybuild/issues/122

**Comment by taiki-e** [comment] 2021-08-11 05:16
FYI: 1.0.34 or older versions of trybuild provide similar behavior to 1.0.44, so you can work around this issue by pinning trybuild to those versions for now.

```toml
trybuild = "=1.0.34"
```

**Closed** 2021-08-15 09:23 UTC
Labels: C-bug, C-enhancement
