### ISSUE TITLE
`cargo llvm-cov report --lcov` fails: No filenames specified!

### ISSUE THREAD

**Issue by DanielT** [taiki-e/cargo-llvm-cov#304] opened 2023-08-22 08:33 UTC
I'm working on a Python module, implemented in Rust using PyO3 (this one: [autosar-data-py](https://github.com/DanielT/autosar-data-py))
Testing it using tests on the Rust side doesn't make sense; I wrote test in Python using pytest instead.
I would also like to generate code coverage from the pytest run.

The workflow for testing is:
1) create and activate a python virtualenv in the project
2) run `maturin develop`, which runs cargo build, builds the Python wheel and installs it into the virtualenv
3) run pytest

To gather coverage info I tried to:
1) Set RUSTFLAGS and LLVM_PROFILE_FILE as shown by `cargo llvm-cov show-env --export-prefix`
2) build the module and run pytest as above
3) run `cargo llvm-cov report --lcov`

This last command fails with the error message "No filenames specified!" and no coverage is generated.

**Comment by taiki-e** [comment] 2023-08-22 10:44
> Set RUSTFLAGS and LLVM_PROFILE_FILE as shown by cargo llvm-cov show-env --export-prefix

You have to set all env vers that show-env shows, not only two env vars.

**Comment by taiki-e** [comment] 2023-08-23 11:37
> only works on Linux, but not on Windows.

Ah, if so, this is probably a duplicate of #300.

**Comment by taiki-e** [comment] 2023-08-23 12:50
Closing as duplicate of https://github.com/taiki-e/cargo-llvm-cov/issues/300 for now.

**Closed by taiki-e** 2023-08-23 12:50 UTC
Labels: C-question
