### ISSUE TITLE
When used with nextest, `--profile <path>` is not being processed correctly

### ISSUE THREAD

**Issue by TriplEight** [taiki-e/cargo-llvm-cov#267] opened 2023-04-28 14:22 UTC
cc https://github.com/taiki-e/cargo-llvm-cov/issues/120

I'm running 
```
NEXTEST_PROFILE="scripts/ci/gitlab/nextest.toml"
cargo llvm-cov nextest run
        --workspace
        --profile testnet
        --verbose
        --locked
        --features=runtime-benchmarks,runtime-metrics
        --no-fail-fast
        --color always
        --verbose
        --include-build-script
        --html
        --output-dir $ARCHIVE
```

And getting an error: 
```
Running `CARGO_INCREMENTAL=0 CARGO_LLVM_COV=1 LLVM_PROFILE_FILE='/builds/TriplEight/target/llvm-cov-target/test-%p-%m.profraw' NEXTEST_TEST_THREADS=1 RUSTFLAGS='-Cdebug-assertions=y -Dwarnings -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target' RUST_TEST_THREADS=1 /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo nextest run --manifest-path /builds/TriplEight/Cargo.toml --target-dir /builds/TriplEight/target/llvm-cov-target run --workspace --profile testnet --locked --features=runtime-benchmarks,runtime-metrics --no-fail-fast --color always -v`
error: profile `scripts/ci/gitlab/nextest.toml not found (known profiles: default, default-miri)`
```

Ran with `--cargo-profile`, like in nextest doc, with the exactly the same result.
Same when I removed `run` after nextest.

Is there any workaround for it by now?

**Comment by taiki-e** [comment] 2023-04-28 14:43
Hmm, this is odd because we already ignore --profile option on nextest.

Could you check does https://github.com/taiki-e/cargo-llvm-cov/commit/ebd846b97608ee8a8c5c5a31216f8f78bd5b0f9c fix this?

(Also please remove `run` after `cargo llvm-cov nextest`.)

**Comment by TriplEight** [comment] 2023-04-28 15:11
Thanks for the quick reply! I ran

```
cargo +stable install --git https://github.com/taiki-e/cargo-llvm-cov cargo-llvm-cov --rev ebd846b97608ee8a8c5c5a31216f8f78bd5b0f9c --force --locked
cargo llvm-cov nextest
        --workspace
        --cargo-profile testnet
        --verbose
        --locked
        --features=runtime-benchmarks,runtime-metrics
        --no-fail-fast
        --color always
        --verbose
        --include-build-script
        --html
        --output-dir $ARCHIVE
```

and got

```
Running `CARGO_INCREMENTAL=0 CARGO_LLVM_COV=1 LLVM_PROFILE_FILE='/builds/TriplEight/target/llvm-cov-target/test-%p-%m.profraw' NEXTEST_TEST_THREADS=1 RUSTFLAGS='-Cdebug-assertions=y -Dwarnings -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target' RUST_TEST_THREADS=1 /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo nextest run --manifest-path /builds/TriplEight/Cargo.toml --target-dir /builds/TriplEight/target/llvm-cov-target --workspace --cargo-profile testnet --locked --features=runtime-benchmarks,runtime-metrics --no-fail-fast --color always -v`
[2023-04-28 15:07:38] error: profile `scripts/ci/gitlab/nextest.toml not found (known profiles: default, default-miri)`
[2023-04-28 15:07:38] error: process didn't exit successfully: `CARGO_INCREMENTAL=0 CARGO_LLVM_COV=1 LLVM_PROFILE_FILE='/builds/TriplEight/target/llvm-cov-target/test-%p-%m.profraw' NEXTEST_TEST_THREADS=1 RUSTFLAGS='-Cdebug-assertions=y -Dwarnings -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target' RUST_TEST_THREADS=1 /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo nextest run --manifest-path /builds/TriplEight/Cargo.toml --target-dir /builds/TriplEight/target/llvm-cov-target --workspace --cargo-profile testnet --locked --features=runtime-benchmarks,runtime-metrics --no-fail-fast --color always -v` (exit status: 96)
```

**Comment by taiki-e** [comment] 2023-04-28 15:28
Hmm... do you have the same problem when running nextest without cargo-llvm-cov?

I guess that it has nothing to do with cargo-llvm-cov, since cargo-llvm-cov does not look at the NEXTEST_PROFILE environment variable and does not change the current directory. (At least in cases where scripts/ci/gitlab/nextest.toml is shown in error.)

**Comment by TriplEight** [comment] 2023-04-28 15:30
No, with nextest I run it normally with `--cargo-profile`. (Maybe the problem is that you're passing the `profile` and not `cargo-profile` [here](https://github.com/taiki-e/cargo-llvm-cov/compare/nextest-profile#diff-b2812f19576dd53d0c35b107a322f58a00fce6977f4b5976e1961853982af3ccR361?))

**Comment by taiki-e** [comment] 2023-04-28 15:52
> I run it normally with `--cargo-profile scripts/ci/gitlab/nextest.toml`.

Um, you seem to be confused about which flag you passed. In logs in your other comments, I did not see any case where you passed scripts/ci/gitlab/nextest.toml to cargo-llvm-cov.

(After unset NEXTEST_PROFILE,) try passing the exact same thing you passed to cargo-nextest to cargo-llvm-cov. https://github.com/taiki-e/cargo-llvm-cov/issues/267#issuecomment-1527674997 's patch should be able to handle it.



> Maybe the problem is that you're passing the `profile` and not `cargo-profile` [here](https://github.com/taiki-e/cargo-llvm-cov/compare/nextest-profile#diff-b2812f19576dd53d0c35b107a322f58a00fce6977f4b5976e1961853982af3ccR361?)

That should work correctly since parse_opt_passthrough refers to the current flag, not the variable name passed. In fact, https://github.com/taiki-e/cargo-llvm-cov/issues/267#issuecomment-1527714964 's log shows that it takes `--cargo-profile testnet` as input and runs `--cargo-profile testnet`:

>  --workspace --cargo-profile testnet --locked

**Comment by taiki-e** [comment] 2023-04-28 16:31
I have confirmed that the https://github.com/taiki-e/cargo-llvm-cov/issues/267#issuecomment-1527674997 's patch locally can handle both options. And opened https://github.com/taiki-e/cargo-llvm-cov/pull/269.

Well, the real complication here is that it was `--cargo-profile` that was not being processed correctly prior to the https://github.com/taiki-e/cargo-llvm-cov/issues/267#issuecomment-1527674997 's patch, and in fact `--profile` is being processed correctly with or without the https://github.com/taiki-e/cargo-llvm-cov/issues/267#issuecomment-1527674997 's patch.

**Comment by taiki-e** [comment] 2023-04-28 17:18
Fixed in v0.5.19

**Comment by TriplEight** [comment] 2023-04-29 12:00
Sorry there was a typo:
> No, with nextest I run it normally with `--cargo-profile scripts/ci/gitlab/nextest.toml`. (Maybe the problem is that you're passing the profile and not cargo-profile here)

I run it normally with `--profile scripts/ci/gitlab/nextest.toml --cargo-profile testnet`

**Comment by TriplEight** [comment] 2023-04-29 12:32
Tested, and can't confirm it's working:
```
Installed package `cargo-llvm-cov v0.5.19` (executable `cargo-llvm-cov`)
$ cargo llvm-cov nextest --workspace --cargo-profile testnet --profile scripts/ci/gitlab/nextest.toml --verbose --locked --features=runtime-benchmarks,runtime-metrics --no-fail-fast --color always --verbose --include-build-script --html --output-dir $ARCHIVE
Running `CARGO_INCREMENTAL=0 CARGO_LLVM_COV=1 LLVM_PROFILE_FILE='/builds/TriplEight/target/llvm-cov-target/test-%p-%m.profraw' NEXTEST_TEST_THREADS=1 RUSTFLAGS='-Cdebug-assertions=y -Dwarnings -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target' RUST_TEST_THREADS=1 /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo nextest run --manifest-path /builds/TriplEight/Cargo.toml --target-dir /builds/TriplEight/target/llvm-cov-target --workspace --cargo-profile testnet --profile scripts/ci/gitlab/nextest.toml --locked --features=runtime-benchmarks,runtime-metrics --no-fail-fast --color always -v`
error: profile `scripts/ci/gitlab/nextest.toml not found (known profiles: default, default-miri)`
error: process didn't exit successfully: `CARGO_INCREMENTAL=0 CARGO_LLVM_COV=1 LLVM_PROFILE_FILE='/builds/TriplEight/target/llvm-cov-target/test-%p-%m.profraw' NEXTEST_TEST_THREADS=1 RUSTFLAGS='-Cdebug-assertions=y -Dwarnings -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target' RUST_TEST_THREADS=1 /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo nextest run --manifest-path /builds/TriplEight/Cargo.toml --target-dir /builds/TriplEight/target/llvm-cov-target --workspace --cargo-profile testnet --profile scripts/ci/gitlab/nextest.toml --locked --features=runtime-benchmarks,runtime-metrics --no-fail-fast --color always -v` (exit status: 96)
```

**Comment by taiki-e** [comment] 2023-04-29 12:47
Hmm, path-based profiles seem to be causing the problem? (I have read [the documentation](https://nexte.st/book/configuration.html), and it is not even clear that such a profile is supported in the first place.)


cc @sunshowers

**Comment by TriplEight** [comment] 2023-04-29 12:51
You are correct, in https://nexte.st/book/running.html there's 
```
--config-file <PATH>
          Config file [default: workspace-root/.config/nextest.toml]
```

And `--profile` reads configured profiles from https://nexte.st/book/configuration.html.
Trying to run with `--config-file scripts/ci/gitlab/nextest.toml`

**Comment by TriplEight** [comment] 2023-04-29 13:01
Now it's working with
```
$ cargo llvm-cov nextest --workspace --cargo-profile testnet --config-file scripts/ci/gitlab/nextest.toml --verbose --locked --features=runtime-benchmarks,runtime-metrics --no-fail-fast --color always --verbose --include-build-script --html --output-dir $ARCHIVE
[2023-04-29 12:55:12]      Running `CARGO_INCREMENTAL=0 CARGO_LLVM_COV=1 LLVM_PROFILE_FILE='/builds/TriplEight/target/llvm-cov-target/test-%p-%m.profraw' NEXTEST_TEST_THREADS=1 RUSTFLAGS='-Cdebug-assertions=y -Dwarnings -C instrument-coverage --cfg=coverage --cfg=trybuild_no_target' RUST_TEST_THREADS=1 /usr/local/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo nextest run --manifest-path /builds/TriplEight/Cargo.toml --target-dir /builds/TriplEight/target/llvm-cov-target --workspace --cargo-profile testnet --config-file scripts/ci/gitlab/nextest.toml --locked --features=runtime-benchmarks,runtime-metrics --no-fail-fast --color always -v`
```

There are no mentions of `config-file` in cargo-llvm-cov code. Checking if it's being passed to nextest.

**Comment by taiki-e** [comment] 2023-04-29 13:14
> There are no mentions of config-file in cargo-llvm-cov code.

cargo-llvm-cov doesn't parse all the cargo-nextest CLI flags, but only those necessary for cargo-llvm-cov to work properly, and just passthrough everything else to the cargo-nextest.

This design eliminates the need to respond to each addition or deletion of CLI flags on the cargo-nextest side and also makes it easier to maintain compatibility with older cargo-nextest.

>  Checking if it's being passed to nextest.

It is passed to cargo-nextest. See this part in the log:

> --cargo-profile testnet  **--config-file scripts/ci/gitlab/nextest.toml**  --verbose

**Comment by taiki-e** [comment] 2023-04-29 13:35
Closing as it has been confirmed that passing the correct option (--config-file) works.

**Closed by taiki-e** 2023-04-29 13:35 UTC
Labels: C-question, A-nextest
