### ISSUE TITLE
[Feature] Output multiple reports in single run.

### ISSUE THREAD

**Issue by tanema** [taiki-e/cargo-llvm-cov#290] opened 2023-07-10 15:28 UTC
## Summary
I would appreciate an ability to be able to output `lcov` and `cobertura` reports from the same run. Since cobertura is coverted from lcov it seems pretty possible. It would also allow me to not have to install more tooling inside my CI to be able to get both reports.

## Example usage
Here is my scenario and reason I need more than one report.
- Gitlab CI
- Gitlab CI coverage tooling requires cobertura. This enables
  - MR coverage changes
  - Coverage report number shown on MR
- I want to generate a entire coverage report for the same large repo.
- The best tooling for this is `genhtml` with `lcov`
- To do both I would need to run the tests twice to generate two reports.

I suspect that there is already a way to generate both reports and I would be happy to learn it as well!

**Comment by taiki-e** [comment] 2023-07-10 15:32
Duplicate of #60.

You can use `cargo llvm-cov report` to get the report without running the test twice.

**Closed by taiki-e** 2023-07-10 15:32 UTC
