### ISSUE TITLE
Less aggressive clean

### ISSUE THREAD

**Issue by smoelius** [taiki-e/cargo-llvm-cov#381] opened 2024-08-07 23:00 UTC
Is there a way now to keep the artifacts that Cargo would produce, but remove everything else (e.g., profraw files)?
https://github.com/taiki-e/cargo-llvm-cov/blob/7d4bb5e99e4d2b865c44932fdeac77b60813f5fc/src/clean.rs#L40-L47

My goal is to run `cargo-llvm-cov` multiple times and not be slowed down by recompilations, but also not have "false positive" reports from previous runs.

If there is no way to do this currently, would you be open to adding such a feature?

**Comment by taiki-e** [comment] 2024-08-08 01:01
Duplicate of #292

I'm happy to accept such a feature.

**Closed by taiki-e** 2024-08-08 01:01 UTC

**Comment by smoelius** [comment] 2024-08-08 09:19
> Duplicate of #292

Ooh, sorry.
