### ISSUE TITLE
Composability with `cargo-careful`

### ISSUE THREAD

**Issue by robo9k** [taiki-e/cargo-llvm-cov#318] opened 2023-09-27 01:59 UTC
I'm trying to combine `cargo-llvm-cov` with [`cargo-careful`](https://github.com/RalfJung/cargo-careful) in a single "cargo test" run.

Via https://github.com/taiki-e/cargo-llvm-cov/blob/main/README.md#get-coverage-of-external-tests
```terminal
$ cargo new --bin example && cd example/
$ source <(cargo +nightly llvm-cov show-env --export-prefix)
$ cargo +nightly llvm-cov clean --workspace
$ cargo +nightly careful setup
[..]
error: could not compile `core` (lib) due to 3688 previous errors; 117 warnings emitted
thread 'main' panicked at 'failed to build sysroot; run `cargo careful setup` to see what went wrong: sysroot build failed'
$ # the above fails, usually one would not run "careful setup" but the steps below
$ cargo +nightly careful test --all-targets --all-features --verbose
$ cargo +nightly llvm-cov report --codecov --output-path codecov.json
```

Without `cargo-llvm-cov` in the mix the "cargo careful test" step _does_ work.

```terminal
$ cargo +nightly --version
cargo 1.74.0-nightly (414d9e3a6 2023-09-22)

$ cargo +nightly llvm-cov --version
cargo-llvm-cov 0.5.33

$ cargo install --list | grep 'cargo-careful v'
cargo-careful v0.4.0:
```

I do not know if that is not possible by design of those two tools? Both docs are a bit spare on what they actually do behind the covers.
Would I just have two separate CI jobs instead?

**Comment by taiki-e** [comment] 2023-09-27 02:16
The problem is that -Zbuild-std is incompatible with -Cinstrument-coverage: https://github.com/rust-lang/rust/issues/79401
(cargo-careful uses its own, not -Zbuild-std, but has the same problem.)

> Would I just have two separate CI jobs instead?

Yeah, you have to use two separate CI jobs at this time.

Closing in favor of the upstream issue.

**Closed by taiki-e** 2023-09-27 02:16 UTC
Labels: C-upstream-bug

**Comment by taiki-e** [comment] 2024-12-07 14:06
UPDATE: -Zbuild-std is now compatible with -Cinstrument-coverage: https://github.com/rust-lang/rust/pull/133369
