### ISSUE TITLE
Build binary with coverage

### ISSUE THREAD

**Issue by f-squirrel** [taiki-e/cargo-llvm-cov#408] opened 2024-12-23 11:43 UTC
Hi,

I noticed that it is possible to run a binary and generate coverage report (`cargo llvm-cov run`), however, this rebuilds the binary.
Is it possible to build and run a binary with instrumentation?

**Comment by taiki-e** [comment] 2024-12-24 18:11
Duplicate of https://github.com/taiki-e/cargo-llvm-cov/issues/373.

**Closed by taiki-e** 2024-12-24 18:11 UTC
